export const productData = {
  "1": {
    id: "1",
    name: "Sony WH-1000XM4 Wireless Headphones",
    brand: "Sony",
    description:
      "Industry-leading noise canceling with Dual Noise Sensor technology. Up to 30-hour battery life with quick charge. Touch Sensor controls to pause play skip tracks, control volume, activate your voice assistant, and answer phone calls.",
    currentPrice: 24999,
    originalPrice: 34999,
    imageUrl: "/images/products/headphones.jpg",
    category: "Electronics",
    rating: 4.8,
    reviews: 2847,
    features: [
      "Industry-leading noise canceling",
      "30-hour battery life",
      "Quick charge (10 min = 5 hours)",
      "Touch sensor controls",
      "Speak-to-chat technology",
      "Wearing detection",
      "Multipoint connection",
    ],
    specifications: {
      "Driver Unit": "40mm dome type",
      "Frequency Response": "4 Hz-40,000 Hz",
      "Battery Life": "30 hours (NC ON), 38 hours (NC OFF)",
      "Charging Time": "3 hours (full charge)",
      Weight: "254g",
      Connectivity: "Bluetooth 5.0, NFC, 3.5mm jack",
      Microphone: "Built-in microphone",
    },
    stores: [
      {
        name: "Amazon India",
        price: 24999,
        url: "https://www.amazon.in/dp/B0863TXGM3",
        logo: "/images/stores/amazon.png",
        rating: 4.3,
        availability: "In Stock",
      },
      {
        name: "Flipkart",
        price: 25999,
        url: "https://www.flipkart.com/sony-wh-1000xm4/p/itm123456789",
        logo: "/images/stores/flipkart.png",
        rating: 4.2,
        availability: "In Stock",
      },
      {
        name: "Croma",
        price: 26499,
        url: "https://www.croma.com/sony-wh-1000xm4",
        logo: "/images/stores/croma.png",
        rating: 4.1,
        availability: "Limited Stock",
      },
    ],
    priceHistory: [
      { date: "2024-01-01", price: 34999 },
      { date: "2024-02-01", price: 32999 },
      { date: "2024-03-01", price: 29999 },
      { date: "2024-04-01", price: 27999 },
      { date: "2024-05-01", price: 25999 },
      { date: "2024-06-01", price: 24999 },
    ],
  },
  "2": {
    id: "2",
    name: "JBL Charge 5 Portable Speaker",
    brand: "JBL",
    description:
      "Take the party with you no matter what the weather. The JBL Charge 5 speaker delivers bold JBL Original Pro Sound, with its optimized long excursion driver, separate tweeter and dual pumping JBL bass radiators.",
    currentPrice: 12999,
    originalPrice: 16999,
    imageUrl: "/images/products/speaker.jpg",
    category: "Electronics",
    rating: 4.6,
    reviews: 1923,
    features: [
      "JBL Pro Sound with optimized driver",
      "20 hours of playtime",
      "IP67 waterproof and dustproof",
      "Wireless Bluetooth streaming",
      "Power bank functionality",
      "PartyBoost feature",
      "Camo and vibrant color options",
    ],
    specifications: {
      "Output Power": "40W RMS",
      "Frequency Response": "65Hz – 20kHz",
      "Battery Life": "Up to 20 hours",
      "Charging Time": "4 hours",
      Weight: "960g",
      Dimensions: "220 x 96 x 93mm",
      "Waterproof Rating": "IP67",
    },
    stores: [
      {
        name: "Amazon India",
        price: 12999,
        url: "https://www.amazon.in/dp/B08T1CQHB4",
        logo: "/images/stores/amazon.png",
        rating: 4.4,
        availability: "In Stock",
      },
      {
        name: "Flipkart",
        price: 13499,
        url: "https://www.flipkart.com/jbl-charge-5/p/itm987654321",
        logo: "/images/stores/flipkart.png",
        rating: 4.3,
        availability: "In Stock",
      },
      {
        name: "JBL Store",
        price: 13999,
        url: "https://in.jbl.com/wireless-speakers/JBL+CHARGE+5.html",
        logo: "/images/stores/jbl.png",
        rating: 4.5,
        availability: "In Stock",
      },
    ],
    priceHistory: [
      { date: "2024-01-01", price: 16999 },
      { date: "2024-02-01", price: 15999 },
      { date: "2024-03-01", price: 14999 },
      { date: "2024-04-01", price: 13999 },
      { date: "2024-05-01", price: 13499 },
      { date: "2024-06-01", price: 12999 },
    ],
  },
  "3": {
    id: "3",
    name: 'Samsung 55" Crystal UHD 4K Smart TV',
    brand: "Samsung",
    description:
      "Experience brilliant picture quality with this Samsung 55-inch Crystal UHD 4K Smart TV. Features Crystal Processor 4K, HDR support, and built-in voice assistants for the ultimate viewing experience.",
    currentPrice: 45999,
    originalPrice: 64999,
    imageUrl: "/images/products/tv.jpg",
    category: "Electronics",
    rating: 4.4,
    reviews: 892,
    features: [
      "Crystal UHD 4K resolution",
      "Crystal Processor 4K",
      "HDR (High Dynamic Range)",
      "Smart TV with Tizen OS",
      "Built-in voice assistants",
      "Multiple connectivity options",
      "Game Mode for enhanced gaming",
    ],
    specifications: {
      "Screen Size": "55 inches",
      Resolution: "3840 x 2160 (4K UHD)",
      "Display Type": "LED",
      "Smart TV": "Yes (Tizen OS)",
      "HDR Support": "HDR10+",
      Connectivity: "3 HDMI, 2 USB, Wi-Fi, Bluetooth",
      Audio: "20W speakers with Dolby Digital Plus",
    },
    stores: [
      {
        name: "Amazon India",
        price: 45999,
        url: "https://www.amazon.in/dp/B08XYQR8VN",
        logo: "/images/stores/amazon.png",
        rating: 4.2,
        availability: "In Stock",
      },
      {
        name: "Flipkart",
        price: 46999,
        url: "https://www.flipkart.com/samsung-55-crystal-uhd-4k/p/itm456789123",
        logo: "/images/stores/flipkart.png",
        rating: 4.1,
        availability: "In Stock",
      },
      {
        name: "Reliance Digital",
        price: 47999,
        url: "https://www.reliancedigital.in/samsung-55-inch-4k-uhd-smart-led-tv",
        logo: "/images/stores/reliance.png",
        rating: 4.0,
        availability: "In Stock",
      },
    ],
    priceHistory: [
      { date: "2024-01-01", price: 64999 },
      { date: "2024-02-01", price: 59999 },
      { date: "2024-03-01", price: 54999 },
      { date: "2024-04-01", price: 49999 },
      { date: "2024-05-01", price: 47999 },
      { date: "2024-06-01", price: 45999 },
    ],
  },
  "4": {
    id: "4",
    name: "MacBook Air 13-inch M2",
    brand: "Apple",
    description:
      "Supercharged by M2 chip. The incredibly thin and light MacBook Air is now more powerful than ever. It delivers exceptional performance and up to 18 hours of battery life.",
    currentPrice: 114900,
    originalPrice: 119900,
    imageUrl: "/images/products/laptop.jpg",
    category: "Electronics",
    rating: 4.9,
    reviews: 1456,
    features: [
      "Apple M2 chip with 8-core CPU",
      "8GB unified memory",
      "256GB SSD storage",
      "13.6-inch Liquid Retina display",
      "1080p FaceTime HD camera",
      "MagSafe 3 charging",
      "Up to 18 hours battery life",
    ],
    specifications: {
      Processor: "Apple M2 chip",
      Memory: "8GB unified memory",
      Storage: "256GB SSD",
      Display: "13.6-inch Liquid Retina",
      Resolution: "2560 x 1664",
      Battery: "Up to 18 hours",
      Weight: "1.24 kg",
    },
    stores: [
      {
        name: "Apple Store India",
        price: 114900,
        url: "https://www.apple.com/in/macbook-air-13-and-15-m2/",
        logo: "/images/stores/apple.png",
        rating: 4.8,
        availability: "In Stock",
      },
      {
        name: "Amazon India",
        price: 116900,
        url: "https://www.amazon.in/dp/B0B3C2R8MP",
        logo: "/images/stores/amazon.png",
        rating: 4.7,
        availability: "In Stock",
      },
      {
        name: "Flipkart",
        price: 117900,
        url: "https://www.flipkart.com/apple-macbook-air-m2/p/itm789123456",
        logo: "/images/stores/flipkart.png",
        rating: 4.6,
        availability: "Limited Stock",
      },
    ],
    priceHistory: [
      { date: "2024-01-01", price: 119900 },
      { date: "2024-02-01", price: 119900 },
      { date: "2024-03-01", price: 117900 },
      { date: "2024-04-01", price: 116900 },
      { date: "2024-05-01", price: 115900 },
      { date: "2024-06-01", price: 114900 },
    ],
  },
  "5": {
    id: "5",
    name: "iPhone 14 128GB",
    brand: "Apple",
    description:
      "iPhone 14. With the most impressive dual-camera system on iPhone. Capture stunning photos in Photographic Styles. Crash Detection, a vital safety feature. All-day battery life.",
    currentPrice: 69900,
    originalPrice: 79900,
    imageUrl: "/images/products/smartphone.jpg",
    category: "Electronics",
    rating: 4.7,
    reviews: 3421,
    features: [
      "6.1-inch Super Retina XDR display",
      "Advanced dual-camera system",
      "A15 Bionic chip",
      "All-day battery life",
      "Crash Detection",
      "Emergency SOS via satellite",
      "Ceramic Shield front",
    ],
    specifications: {
      Display: "6.1-inch Super Retina XDR",
      Chip: "A15 Bionic",
      Storage: "128GB",
      Camera: "Dual 12MP system",
      Video: "4K Dolby Vision HDR",
      Battery: "Up to 20 hours video playback",
      "Water Resistance": "IP68",
    },
    stores: [
      {
        name: "Apple Store India",
        price: 69900,
        url: "https://www.apple.com/in/iphone-14/",
        logo: "/images/stores/apple.png",
        rating: 4.8,
        availability: "In Stock",
      },
      {
        name: "Amazon India",
        price: 70900,
        url: "https://www.amazon.in/dp/B0BDJ3CQPX",
        logo: "/images/stores/amazon.png",
        rating: 4.6,
        availability: "In Stock",
      },
      {
        name: "Flipkart",
        price: 71900,
        url: "https://www.flipkart.com/apple-iphone-14-128gb/p/itm321654987",
        logo: "/images/stores/flipkart.png",
        rating: 4.5,
        availability: "In Stock",
      },
    ],
    priceHistory: [
      { date: "2024-01-01", price: 79900 },
      { date: "2024-02-01", price: 77900 },
      { date: "2024-03-01", price: 75900 },
      { date: "2024-04-01", price: 73900 },
      { date: "2024-05-01", price: 71900 },
      { date: "2024-06-01", price: 69900 },
    ],
  },
  "6": {
    id: "6",
    name: "Apple Watch Series 9 GPS 45mm",
    brand: "Apple",
    description:
      "Apple Watch Series 9 features the S9 chip, a magical new way to use your watch without touching the screen, and a brighter display. Advanced health, safety, and activity features provide powerful insights.",
    currentPrice: 42900,
    originalPrice: 45900,
    imageUrl: "/images/products/smartwatch.jpg",
    category: "Electronics",
    rating: 4.8,
    reviews: 987,
    features: [
      "S9 SiP with 64-bit dual-core processor",
      "Double Tap gesture",
      "Up to 2000 nits brightness",
      "Advanced health monitoring",
      "Crash Detection",
      "Water resistant to 50 metres",
      "All-day 18-hour battery life",
    ],
    specifications: {
      "Case Size": "45mm",
      Display: "Always-On Retina LTPO OLED",
      Brightness: "Up to 2000 nits",
      Chip: "S9 SiP",
      Storage: "64GB",
      Battery: "Up to 18 hours",
      "Water Resistance": "50 metres",
    },
    stores: [
      {
        name: "Apple Store India",
        price: 42900,
        url: "https://www.apple.com/in/apple-watch-series-9/",
        logo: "/images/stores/apple.png",
        rating: 4.9,
        availability: "In Stock",
      },
      {
        name: "Amazon India",
        price: 43900,
        url: "https://www.amazon.in/dp/B0CHX9CY7W",
        logo: "/images/stores/amazon.png",
        rating: 4.7,
        availability: "In Stock",
      },
      {
        name: "Croma",
        price: 44900,
        url: "https://www.croma.com/apple-watch-series-9-gps-45mm",
        logo: "/images/stores/croma.png",
        rating: 4.6,
        availability: "In Stock",
      },
    ],
    priceHistory: [
      { date: "2024-01-01", price: 45900 },
      { date: "2024-02-01", price: 45900 },
      { date: "2024-03-01", price: 44900 },
      { date: "2024-04-01", price: 44900 },
      { date: "2024-05-01", price: 43900 },
      { date: "2024-06-01", price: 42900 },
    ],
  },
}

export function getProductById(id: string) {
  return productData[id as keyof typeof productData] || null
}

export function getAllProducts() {
  return Object.values(productData)
}
